### ISSUE TITLE
list index out of range while parsing s2gs

### ISSUE THREAD

**Issue by dsjoerg** [ggtracker/sc2reader#3] opened 2012-10-24 02:16 UTC
The following output is from a new test case in ggpyjobs.

The s2gs is originally from http://eu.depot.battle.net:1119/49e7be5d753cc21c236cad4f757540fd283ea65df534566698dfcf454ad5e7f5.s2gs

```
======================================================================
ERROR: test_s2gs_parse_lioor (sc2parse.tests.SC2ReaderToEsdbTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/david/Dropbox/Programming/esdb/esdb/vendor/ggpyjobs/sc2parse/tests.py", line 156, in test_s2gs_parse_lioor
    s2gs = self.get_parsed_s2gs(11)
  File "/Users/david/Dropbox/Programming/esdb/esdb/vendor/ggpyjobs/sc2parse/tests.py", line 68, in get_parsed_s2gs
    summary = ggfactory.load_game_summary(s2gsfile)
  File "/Users/david/Dropbox/Programming/esdb/esdb/vendor/ggpyjobs/src/sc2reader/sc2reader/factories.py", line 92, in load_game_summary
    return self.load(GameSummary, source, options, **new_options)
  File "/Users/david/Dropbox/Programming/esdb/esdb/vendor/ggpyjobs/src/sc2reader/sc2reader/factories.py", line 137, in load
    return self._load(cls, resource, filename=filename, options=options)
  File "/Users/david/Dropbox/Programming/esdb/esdb/vendor/ggpyjobs/src/sc2reader/sc2reader/factories.py", line 147, in _load
    obj = cls(resource, filename=filename, factory=self, **options)
  File "/Users/david/Dropbox/Programming/esdb/esdb/vendor/ggpyjobs/src/sc2reader/sc2reader/resources.py", line 721, in __init__
    self.load_translations()
  File "/Users/david/Dropbox/Programming/esdb/esdb/vendor/ggpyjobs/src/sc2reader/sc2reader/resources.py", line 803, in load_translations
    translation[uid] = sheets[sheet][item]
IndexError: list index out of range
```

**Comment by GraylinKim** [comment] 2012-10-25 15:17
Duplicate of #2. Both are due to the same localization issue.

**Closed as completed by GraylinKim** 2012-10-25 15:17 UTC
