### ISSUE TITLE
KeyError with certain s2gs files

### ISSUE THREAD

**Issue by dsjoerg** [ggtracker/sc2reader#1] opened 2012-10-04 18:14 UTC
For example, with 0effa8abed1a61db2f377c213c65334fa62626e2dcceef94d67bb51dc8585560.s2gs,

```
Traceback (most recent call last):
  File "/Users/david/Dropbox/Programming/esdb/esdb/vendor/ggpyjobs/sc2parse/tests.py", line 144, in test_s2gs_parse
    s2gs = self.get_parsed_s2gs(3)
  File "/Users/david/Dropbox/Programming/esdb/esdb/vendor/ggpyjobs/sc2parse/tests.py", line 65, in get_parsed_s2gs
    summary = sc2reader.load_game_summary(s2gsfile)
  File "/Users/david/Dropbox/Programming/sc2reader_ggtracker/sc2reader/sc2reader/factories.py", line 92, in load_game_summary
    return self.load(GameSummary, source, options, **new_options)
  File "/Users/david/Dropbox/Programming/sc2reader_ggtracker/sc2reader/sc2reader/factories.py", line 137, in load
    return self._load(cls, resource, filename=filename, options=options)
  File "/Users/david/Dropbox/Programming/sc2reader_ggtracker/sc2reader/sc2reader/factories.py", line 147, in _load
    obj = cls(resource, filename=filename, factory=self, **options)
  File "/Users/david/Dropbox/Programming/sc2reader_ggtracker/sc2reader/sc2reader/resources.py", line 716, in __init__
    self.load_player_builds()
  File "/Users/david/Dropbox/Programming/sc2reader_ggtracker/sc2reader/sc2reader/resources.py", line 904, in load_player_builds
    order_name = self.translations['enUS'][build_item[0][1]]
KeyError: 83886080
```

**Comment by dsjoerg** [comment] 2012-10-04 18:25
I pushed a change so that rather than dying, it simply notes the problem, uses "Unknown" as the build item, and moves on.

What this issue is for is finding out what 83886080 really is -- perhaps in a localization file.

Depending on how many Unknowns are in typical Ladder s2gs files, this might be a low priority task.

**Comment by GraylinKim** [comment] 2012-10-04 19:05
Alright, the patch looks fine for now. I'll probably fix it to use the logger instead of a print statement later.

I'll investigate the missing keys after I push the SC2Factory with caching.

**Comment by GraylinKim** [comment] 2012-10-05 13:01
Can you confirm if you've seen this in any non-beta files @dsjoerg?

I did an inventory over all the s2gs files I have on hand and key errors only came up in beta s2gs files. I also followed up on them in the build order tab and they don't appear in the UI. If you cut out the 'Unknown' entries the build orders parse perfectly.

I'm going to suggest that instead of adding them to the build we log the issue and ignore the entry.

**Comment by dsjoerg** [comment] 2012-10-05 13:09
Confirmed, I've seen this in non-beta files.  The example I gave in this
issue is a non-beta game I played 9 days ago:
http://ggtracker.com/matches/400301

Good idea to log the issue and ignore the entry, I'll leave that to you.

**Comment by GraylinKim** [comment] 2012-10-05 18:12
I agree that the non-beta s2gs files can have localization look-up misses.

Since these misses don't seem to affect the player stats or build order parsing I vote to close the issue. If this ever does cause any issues in the future the log message should help us identify the root cause and open a new more targeted issue.

**Closed as completed by GraylinKim** 2012-10-05 18:12 UTC

**Comment by dsjoerg** [comment] 2012-10-05 18:23
Agreed
