### ISSUE TITLE
Numerous errors logged when running test_all.py

### ISSUE THREAD

**Issue by Unclevinny** [ggtracker/sc2reader#43] opened 2018-01-24 20:19 UTC
I just forked from https://github.com/ggtracker/sc2reader (the upstream branch) on Windows 10 (Python 3.6.4) and ran test_all.py

This generates a ton of logs, much of which look like errors, such as:
```
Whoa! 'CreepTracker' object has no attribute 'creepTracker'
...
Unable to change type of None [4C80001] to SpecialNexus [frame 8345]; unit type not found in build base
...
Conflicting results for Team 1: {'Loss', 'Win', None}
...
Bad upkeep_pid (4) for event <class 'sc2reader.events.tracker.UnitBornEvent'> at 00.00 [0].

```
....etc.... and at the end there are 4 tracebacks and a status message:
```
======================================================================
ERROR: test_33_shift_click_calldown_mule (__main__.TestReplays)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_replays/test_all.py", line 512, in test_33_shift_click_calldown_mule
    self.assertEqual(len(filter(efilter, replay.events)), 29)
TypeError: object of type 'filter' has no len()

======================================================================
ERROR: test_33_shift_click_spawn_larva (__main__.TestReplays)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_replays/test_all.py", line 518, in test_33_shift_click_spawn_larva
    self.assertEqual(len(filter(efilter, replay.events)), 23)
TypeError: object of type 'filter' has no len()

======================================================================
ERROR: test_creepTracker (__main__.TestReplays)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_replays/test_all.py", line 387, in test_creepTracker
    assert replay.player[player_id].max_creep_spread[1] >0
AttributeError: 'Participant' object has no attribute 'max_creep_spread'

======================================================================
ERROR: test_lotv_creepTracker (__main__.TestReplays)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_replays/test_all.py", line 434, in test_lotv_creepTracker
    assert replay.player[player_id].max_creep_spread >0
AttributeError: 'Participant' object has no attribute 'max_creep_spread'

----------------------------------------------------------------------
Ran 60 tests in 30.223s

FAILED (errors=4, expected failures=3)
```

You can find the entire output here: https://pastebin.com/BFCSdSN2
I made a post about this in our Google Group and it was recommended that I log a bug: https://groups.google.com/d/msg/sc2reader/3bTRTrVoGm0/c-Ol8kgNDQAJ

Let me know if you'd like more troubleshooting info!

**Comment by Unclevinny** [comment] 2018-01-24 22:00
I've narrowed it down to the first problem that pops up:
  File "C:\Users\Vince\py\sc2reader2\sc2reader\engine\plugins\creeptracker.py", line 121, in __init__
    mapsio = StringIO(replayMap.minimap)
TypeError: initial_value must be str or None, not bytes

**Comment by dsjoerg** [comment] 2018-01-24 22:03
I wonder if the problem is specific to Windows, or the python version, or
the particulars of your install.

**Comment by Unclevinny** [comment] 2018-01-25 05:33
Some more notes on the tests that are printing a lot of messages to the log. (These are all tested w/ Python 3.6.4 so far.)

This test should fail, and does, but puts a ton of log messages out:
    @unittest.expectedFailure
    def test_outmatched_pids(self):
    
This test passes, but includes logging & deprecation notices:
        def test_gameheartnormalizer_plugin(self):
    
Also fails w/ errors:
    def test_lotv_creepTracker(self):
    
Passes, but puts out a lot of logs:
  def test_31(self):        
  
Passes, but puts out a few "missing ability" logs:
  def test_30_apms(self):
  
Passes, but puts out a few "missing ability" logs:
    def test_38749(self):
    
Passes, but has a lot of "missing ability" logs
     def test_38996(self):
        replay = sc2reader.load_replay("test_replays/3.0.0.38996/1.SC2Replay")
        self.assertEqual(replay.expansion, 'LotV')
        replay = sc2reader.load_replay("test_replays/3.0.0.38996/2.SC2Replay")
        self.assertEqual(replay.expansion, 'LotV')
        
Passes, but has many "unable to change type of None..." log statements
    def test_funny_minerals(self):

**Comment by cclauss** [comment] 2018-04-13 12:28
The __filter()__ issues only appear on __Python 3__.  See #47 

These two issues are easy to fix by wrapping __len(filter())__ as follows: __len(list(filter()))__.  See:https://github.com/ggtracker/sc2reader/pull/47/commits/ff56eaa9eab13f963953505ab9b3452677435f8c

**Comment by cclauss** [comment] 2018-04-23 07:32
Can we change the title of this issue to __CreepTracker object has no attribute creepTracker__ or are there other problems still unfixed under this issue?  I can not even find __test_all.py__

**Comment by StoicLoofah** [comment] 2018-04-24 03:22
I think the best thing to do is to create a new issue and link it to this one as history. Once that's open, I'll close this issue. Thanks for helping to stay on top of everything!

**Comment by StoicLoofah** [comment] 2018-05-15 00:01
With #55 we have a clean circleci build for python3. I'm going to close this issue for now. Please reply if you're still seeing issues, and we can either reopen or create a new issue then

**Closed as completed by StoicLoofah** 2018-05-15 00:01 UTC
